// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:acd2d7df-cb30-4800-806a-6761b441d7a1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sBE2yp23R",
    "aws_user_pools_web_client_id": "5g4vnqlhaqj3cltv0op1dku96i",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "organization-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "user-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "settings-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "gauge-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "access-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "payment-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "readings-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "news-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "analysisTemplate-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "waterAnalysis-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "templateList-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "headwater",
            "endpoint": "https://yzfv1i5iz8.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "dev-admin.headwater.at-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://dev-admin.headwater.at-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
